[package]
name = "gtk-rust-template"
version = "0.1.0"
authors = ["Bilal Elmoussaoui <bil.elmoussaoui@gmail.com>", "Relm4 maintainers"]
edition = "2021"
publish = false

[dependencies]
gettext-rs = { version = "0.7", features = ["gettext-system"] }
gtk = { version = "0.4", package = "gtk4" }
log = "0.4"
once_cell = "1.14"
pretty_env_logger = "0.4"
relm4 = { git = "https://github.com/Relm4/Relm4", features = ["macros"] }