[package]
name = "gtk-rust-template"
version = "0.1.0"
authors = ["Bilal Elmoussaoui <bil.elmoussaoui@gmail.com>", "Relm4 maintainers"]
edition = "2021"
publish = false

[dependencies]
log = "0.4"
pretty_env_logger = "0.4"
gettext-rs = { version = "0.7", features = ["gettext-system"] }
once_cell = "1.9"
relm4 = { git = "https://github.com/Relm4/Relm4", branch = "next", features = ["macros"] }

